### ISSUE TITLE
Generate a directory and output all files into the directory.

### ISSUE THREAD

**Issue by youngchanpark** [hmgu-itg/man_qq_annotate#4]
Current version (v0.2.0) accepts an output prefix and generates all files based on the output prefix.

For example, if the parsed prefix is `/path/to/dir/prefix`, the following four output files will be generated: 
- `/path/to/dir/prefix.run_conf`
- `/path/to/dir/prefix.qq.png`
- `/path/to/dir/prefix.lambda.txt`
- `/path/to/dir/prefix.man.png`

What would be better is for manqq to first make a new directory and output the files to the directory.

For example, if `/path/to/dir/output` was parsed to the output argument, that directory would first be created and all output files (the four above) should all be generated in that directory.  

We would also need to add a `--overwrite` option so that the user can overwrite the output directory if it already exists.

**Comment by agilly** [comment]
I disagree, output prefix similar to plink works well.
